// Expo config plugin: expose the StarXpand SDK's bundled AAR to Gradle.
//
// react-native-star-io10 resolves its native stario10.aar via a flatDir
// repository declared only in ITS OWN project. Gradle resolves the :app
// configurations using :app's repositories, so the AAR is invisible there
// ("Could not find :stario10:"). Star's README documents the fix: add the
// flatDir to allprojects.repositories in the ROOT build.gradle. Because
// android/ is regenerated by prebuild, we inject it here so the fix survives
// every local/EAS prebuild.

const { withProjectBuildGradle } = require('@expo/config-plugins');

const FLAT_DIR = `flatDir { dirs "$rootDir/../node_modules/react-native-star-io10/android/src/lib" }`;

const withStarPrinterFlatDir = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes('react-native-star-io10/android/src/lib')) {
      return cfg; // already injected
    }
    const replaced = cfg.modResults.contents.replace(
      /allprojects\s*\{\s*repositories\s*\{/,
      (match) => `${match}\n        ${FLAT_DIR}`,
    );
    if (replaced === cfg.modResults.contents) {
      throw new Error(
        '[withStarPrinterFlatDir] Could not find allprojects.repositories in android/build.gradle — template changed?',
      );
    }
    cfg.modResults.contents = replaced;
    return cfg;
  });

module.exports = withStarPrinterFlatDir;
