// Alert player — the custom Vizio Food new-order alert.
//
// Sound: assets/sounds/new-order-alert.wav — an original, loud multi-tone
// kitchen chime (generated by scripts/gen-alert-sound.cjs; deliberately NOT
// copied from any other product). Volume, repeat count and repeat interval
// are user settings; repeatCount=0 means "repeat until acknowledged".
//
// Playback runs through expo-audio with playsInSilentMode so the alert is
// audible even when the tablet is muted. Vibration uses the platform
// Vibration API with a distinctive pattern.

import { Vibration } from 'react-native';
import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import type { KitchenOrder } from '../lib/types';
import { getSettings } from '../state/settingsStore';
import { isUnacknowledged } from '../lib/orderLogic';

let player: ReturnType<typeof createAudioPlayer> | null = null;
let modeConfigured = false;
let repeatTimer: ReturnType<typeof setTimeout> | null = null;
let playsRemaining = 0;
let currentOrderId: string | null = null;

const VIBRATION_PATTERN = [0, 500, 200, 500, 200, 800];

async function ensureAudioMode(): Promise<void> {
  if (modeConfigured) return;
  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      shouldPlayInBackground: false,
      interruptionMode: 'doNotMix',
    });
    modeConfigured = true;
  } catch {
    // Older configurations may reject some options — retry minimal mode.
    try {
      await setAudioModeAsync({ playsInSilentMode: true });
      modeConfigured = true;
    } catch {
      // give up silently; sound may still play
    }
  }
}

function ensurePlayer() {
  if (!player) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const source = require('../../assets/sounds/new-order-alert.wav');
    player = createAudioPlayer(source);
  }
  return player;
}

function playOnce(): void {
  try {
    const p = ensurePlayer();
    p.volume = getSettings().volume;
    p.seekTo(0);
    p.play();
  } catch {
    // Never let an audio problem crash the alert path.
  }
}

function vibrate(): void {
  try {
    if (getSettings().vibrationEnabled) Vibration.vibrate(VIBRATION_PATTERN, false);
  } catch {
    // ignore
  }
}

/** Stop any scheduled repeats and vibration. */
export function stopAlert(): void {
  if (repeatTimer) {
    clearTimeout(repeatTimer);
    repeatTimer = null;
  }
  playsRemaining = 0;
  currentOrderId = null;
  try {
    Vibration.cancel();
  } catch {
    // ignore
  }
}

/**
 * Play the new-order alert. Honors settings:
 *   soundEnabled, volume, repeatCount (0 = until acknowledged),
 *   repeatIntervalSec, vibrationEnabled.
 *
 * The repeat loop re-checks the store: repeats stop as soon as the order is
 * acknowledged (or advanced, or no longer alert-worthy).
 */
export async function playNewOrderAlert(order: KitchenOrder): Promise<void> {
  const settings = getSettings();
  stopAlert();
  currentOrderId = order.id;

  if (!settings.soundEnabled && !settings.vibrationEnabled) return;

  await ensureAudioMode();

  if (settings.vibrationEnabled) vibrate();
  if (settings.soundEnabled) playOnce();

  if (settings.repeatCount === 0) {
    playsRemaining = Number.POSITIVE_INFINITY; // until acknowledged
  } else {
    playsRemaining = Math.max(0, settings.repeatCount - 1);
  }
  scheduleNextRepeat();
}

function scheduleNextRepeat(): void {
  if (playsRemaining <= 0) return;
  const settings = getSettings();
  repeatTimer = setTimeout(() => {
    void (async () => {
      // Stop conditions: order gone, acknowledged, advanced out of New.
      const { getOrder } = await import('../state/ordersStore');
      const order = currentOrderId ? getOrder(currentOrderId) : null;
      if (!order || !isUnacknowledged(order)) {
        stopAlert();
        return;
      }
      if (settings.soundEnabled) playOnce();
      if (settings.vibrationEnabled) vibrate();
      playsRemaining -= 1;
      scheduleNextRepeat();
    })();
  }, Math.max(3, settings.repeatIntervalSec) * 1000);
}

/** TEST NEW ORDER SOUND — the exact sound/volume used for real orders. */
export async function testAlertSound(): Promise<void> {
  await ensureAudioMode();
  const settings = getSettings();
  if (settings.vibrationEnabled) vibrate();
  if (settings.soundEnabled) {
    playOnce();
    // One repeat so staff can confirm audibility from across the kitchen.
    setTimeout(() => {
      if (currentOrderId === null) playOnce();
    }, 2500);
  }
}
