// Alert player — plays the custom Vizio Food new-order sound ONCE.
//
// New orders no longer drive an in-app alert: they raise ONE Android
// heads-up notification (channel 'orders' carries the same custom sound and
// vibration — see notifications.ts). This module only serves the Settings
// "TEST ORDER SOUND" button, so staff can verify audibility without an
// order. The repeat-until-acknowledged loop was removed by design: nothing
// may keep ringing or block the app because an order is unacknowledged.
//
// Sound: assets/sounds/new-order-alert.wav — an original, loud multi-tone
// kitchen chime (generated by scripts/gen-alert-sound.cjs).

import { Vibration } from 'react-native';
import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import { getSettings } from '../state/settingsStore';

let player: ReturnType<typeof createAudioPlayer> | null = null;
let modeConfigured = false;

const VIBRATION_PATTERN = [0, 500, 200, 500, 200, 800];

async function ensureAudioMode(): Promise<void> {
  if (modeConfigured) return;
  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      shouldPlayInBackground: false,
      interruptionMode: 'doNotMix',
    });
    modeConfigured = true;
  } catch {
    // Older configurations may reject some options — retry minimal mode.
    try {
      await setAudioModeAsync({ playsInSilentMode: true });
      modeConfigured = true;
    } catch {
      // give up silently; sound may still play
    }
  }
}

function ensurePlayer() {
  if (!player) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const source = require('../../assets/sounds/new-order-alert.wav');
    player = createAudioPlayer(source);
  }
  return player;
}

function playOnce(): void {
  try {
    const p = ensurePlayer();
    p.volume = getSettings().volume;
    p.seekTo(0);
    p.play();
  } catch {
    // Never let an audio problem crash anything.
  }
}

/** TEST NEW ORDER SOUND — the exact sound/volume used by the notification channel test. */
export async function testAlertSound(): Promise<void> {
  await ensureAudioMode();
  const settings = getSettings();
  if (settings.vibrationEnabled) {
    try {
      Vibration.vibrate(VIBRATION_PATTERN, false);
    } catch {
      // ignore
    }
  }
  if (settings.soundEnabled) {
    playOnce();
    // One repeat so staff can confirm audibility from across the kitchen.
    setTimeout(() => playOnce(), 2500);
  }
}
