import { useEffect, useRef, useState } from 'react'; import { Link, useSearchParams } from 'react-router-dom'; import { AlertCircle, CheckCircle2, Loader2, XCircle } from 'lucide-react'; import { clearCart, readCart, writeCart } from '../cart';
// The cart is only cleared after the server (verify-checkout-session Edge
// Function, using STRIPE_SECRET_KEY server-side) confirms this Checkout
// Session is complete AND paid. A session_id in the URL alone proves nothing.
const verifyEndpoint=import.meta.env.VITE_CHECKOUT_VERIFY_ENDPOINT;
type VerifyState='verifying'|'paid'|'unconfirmed';
async function verifySessionPaid(sessionId:string):Promise<boolean>{if(!verifyEndpoint)return false;try{const response=await fetch(verifyEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId})});if(!response.ok)return false;const payload=await response.json() as {paid?:boolean};return payload.paid===true}catch{return false}}
export function CheckoutSuccess(){const [params]=useSearchParams();const sessionId=params.get('session_id');const [state,setState]=useState<VerifyState>(sessionId?'verifying':'unconfirmed');const cleared=useRef(false);
useEffect(()=>{if(!sessionId)return;let active=true;void verifySessionPaid(sessionId).then(paid=>{if(!active)return;if(paid&&!cleared.current){cleared.current=true;writeCart(clearCart(readCart()))}setState(paid?'paid':'unconfirmed')});return()=>{active=false}},[sessionId]);
if(state==='verifying')return <main className="empty"><Loader2 className="spin" size={50}/><p className="eyebrow">Confirming payment</p><h1>One moment…</h1><p>We are confirming your payment with Stripe. Please keep this page open.</p></main>;
if(state==='unconfirmed')return <main className="empty"><AlertCircle size={50}/><p className="eyebrow">Payment not confirmed</p><h1>We couldn't confirm this payment.</h1><p>No completed payment was found for this visit. Your cart has been saved — if you were charged, your order is safe and will appear under My account once confirmed.</p><div className="actions" style={{justifyContent:'center'}}><Link className="button" to="/checkout">Return to checkout</Link><Link className="textlink" to="/">Return home</Link></div></main>;
return <main className="empty"><CheckCircle2 size={50}/><p className="eyebrow">Payment successful</p><h1>Grazie.</h1><p>Your order has been confirmed and is now with the kitchen.</p><Link className="button" to="/">Return home</Link></main>}
export function CheckoutCancel(){return <main className="empty"><XCircle size={50}/><p className="eyebrow">Payment cancelled</p><h1>Your cart is saved.</h1><p>No payment was taken.</p><Link className="button" to="/checkout">Return to checkout</Link></main>}
