import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, MapPin, Package, Phone, Printer, Search, Truck, XCircle } from 'lucide-react';
import { Modal, PageTitle, Status } from './components';
import { getOrders, getProducts, updateOrderStatus } from './supabase';
import { useResource } from './useResource';
import { useOrdersRealtime } from '../hooks/useOrdersRealtime';
import { useToast } from '../components/Toast';
import { playNewPaidOrderSound } from './orderNotifications';
import type { Order, OrderStatus } from './types';

const statuses: OrderStatus[] = ['New', 'Accepted', 'Preparing', 'Ready', 'Completed', 'Rejected'];
const counters: OrderStatus[] = ['New', 'Accepted', 'Preparing', 'Ready', 'Completed'];
const money = (value:number) => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(value);
const elapsed = (createdAt:string) => { const minutes=Math.max(0,Math.floor((Date.now()-new Date(createdAt).getTime())/60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.floor(minutes/60)}h ${minutes%60}m ago`; };
const nextActions: Record<OrderStatus, OrderStatus[]> = { New:['Accepted','Rejected'], Accepted:['Preparing'], Preparing:['Ready'], Ready:['Completed'], Completed:[], Rejected:[] };

function Payment({ status }: { status:Order['paymentStatus'] }) { return <span className={`payment-status ${status}`}>{status === 'unknown' ? 'Payment unknown' : status}</span>; }

function StatusActions({ order, onChange, compact = false }: { order:Order; onChange:(order:Order,status:OrderStatus)=>void; compact?:boolean }) {
  const actions=nextActions[order.status];
  if (!actions.length) return <span className="order-final">Finalised</span>;
  return <div className={`order-actions ${compact?'compact':''}`}>{actions.map(status=><button key={status} className={status==='Rejected'?'order-reject':'admin-primary'} onClick={()=>onChange(order,status)}>{status==='Rejected'?<XCircle size={15}/>:<CheckCircle2 size={15}/>} {status}</button>)}</div>;
}

function OrderedItems({ order, compact = false }: { order:Order; compact?:boolean }) {
  if (!order.items.length) return <p className="order-items-empty">{order.itemsCount} item{order.itemsCount===1?'':'s'} · item details unavailable</p>;
  return <ul className={`ordered-items ${compact?'compact':''}`}>{order.items.map(item=><li key={item.id}><b>{item.quantity}× {item.name}</b>{!compact && <><span>{money(item.unitPrice * item.quantity)}{item.modifiers.length ? ` · ${item.modifiers.join(', ')}` : ''}</span>{item.notes && <small>{item.notes}</small>}</>}</li>)}</ul>;
}

function OrderDetail({ order, close, onChange }: { order:Order; close:()=>void; onChange:(order:Order,status:OrderStatus)=>void }) {
  return <Modal title={order.orderNumber} onClose={close}><section className="order-detail"><div className="order-detail-summary"><div><Status value={order.status}/><Payment status={order.paymentStatus}/></div><b>{money(order.total)}</b></div><div className="order-contact"><strong>{order.customer}</strong><a href={`tel:${order.phone}`}><Phone size={14}/>{order.phone || 'No phone supplied'}</a><a href={`mailto:${order.email}`}>{order.email}</a></div><p className="order-fulfilment">{order.fulfilment==='Delivery'?<Truck size={16}/>:<MapPin size={16}/>}{order.fulfilment} · <Clock3 size={15}/>{elapsed(order.createdAt)}</p><section><h3>Ordered items</h3><OrderedItems order={order}/></section>{order.notes && <section><h3>Order notes</h3><p className="order-notes">{order.notes}</p></section>}<div className="order-detail-actions"><StatusActions order={order} onChange={onChange}/></div></section></Modal>;
}

function OrderCard({ order, onChange, onSelect }: { order:Order; onChange:(order:Order,status:OrderStatus)=>void; onSelect:(order:Order)=>void }) {
  return <article className={`live-order status-${order.status.toLowerCase()}`}><header><div><button className="order-link" onClick={()=>onSelect(order)}>{order.orderNumber}</button><small><Clock3 size={13}/>{elapsed(order.createdAt)}</small></div><div><Status value={order.status}/><Payment status={order.paymentStatus}/></div></header><div className="live-order-meta"><span>{order.fulfilment==='Delivery'?<Truck size={16}/>:<MapPin size={16}/>}{order.fulfilment}</span><strong>{money(order.total)}</strong></div><div className="live-order-customer"><b>{order.customer}</b><a href={`tel:${order.phone}`}><Phone size={13}/>{order.phone || 'No phone supplied'}</a><small>{order.email}</small></div><OrderedItems order={order} compact/>{order.notes && <p className="order-notes"><b>Notes:</b> {order.notes}</p>}<footer><button className="table-button" onClick={()=>onSelect(order)}>View order</button><StatusActions order={order} onChange={onChange} compact/></footer></article>;
}

function exportOrders(orders:Order[]) { const rows=[['Order','Customer','Phone','Email','Fulfilment','Payment','Status','Total','Placed'],...orders.map(order=>[order.orderNumber,order.customer,order.phone,order.email,order.fulfilment,order.paymentStatus,order.status,String(order.total),order.createdAt])]; const url=URL.createObjectURL(new Blob([rows.map(row=>row.map(value=>`"${value.replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv'})); const link=document.createElement('a'); link.href=url; link.download='vizio-orders.csv'; link.click(); URL.revokeObjectURL(url); }

export function EnhancedOrders(){
  const resource=useResource(getOrders); const toast=useToast(); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'All'|OrderStatus>('All'); const [selected,setSelected]=useState<Order>(); const [page,setPage]=useState(1); const pageSize=12;
  const [,setClock]=useState(0); useEffect(()=>{const timer=window.setInterval(()=>setClock(value=>value+1),60000);return()=>window.clearInterval(timer)},[]);
  const refresh=useCallback((event?:{eventType?:string;new?:Record<string,unknown>})=>{if(event?.eventType==='INSERT'&&String(event.new?.payment_status??'paid').toLowerCase()==='paid'){playNewPaidOrderSound();toast.show(`New paid order ${String(event.new?.order_number??'')} received`);} void resource.reload();},[resource.reload,toast]); useOrdersRealtime(refresh);
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return(resource.data??[]).filter(order=>(!term||[order.orderNumber,order.customer,order.phone,order.email].some(value=>value.toLowerCase().includes(term)))&&(status==='All'||order.status===status));},[resource.data,query,status]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)); const visible=filtered.slice((page-1)*pageSize,page*pageSize); const totals=useMemo(()=>Object.fromEntries(counters.map(value=>[value,(resource.data??[]).filter(order=>order.status===value).length])) as Record<OrderStatus,number>,[resource.data]);
  const update=async(order:Order,next:OrderStatus)=>{try{await updateOrderStatus(order.orderId,next);toast.show(`${order.orderNumber} marked ${next}`);await resource.reload();setSelected(current=>current?.orderId===order.orderId?{...current,status:next}:current);}catch(error){toast.show(error instanceof Error?error.message:'Could not update order.','error')}};
  return <section className="admin-page live-orders-page"><PageTitle title="Orders"><div className="admin-actions"><button className="admin-secondary" onClick={()=>exportOrders(filtered)}><Download size={16}/>Export CSV</button><button className="admin-secondary" onClick={()=>window.print()}><Printer size={16}/>Print</button></div></PageTitle><section className="live-order-counters" aria-label="Order status counts">{counters.map(value=><button key={value} className={status===value?'active':''} onClick={()=>{setStatus(status===value?'All':value);setPage(1)}}><span>{value}</span><b>{totals[value]}</b></button>)}</section><section className="admin-card order-toolbar"><label className="admin-search"><Search size={17}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search order, customer, phone or email" aria-label="Search orders"/></label><select value={status} onChange={event=>{setStatus(event.target.value as 'All'|OrderStatus);setPage(1)}} aria-label="Filter by status"><option value="All">All statuses</option>{statuses.map(value=><option key={value} value={value}>{value}</option>)}</select></section><section className="live-order-grid">{resource.loading?<p className="admin-message">Loading orders…</p>:resource.error?<p className="admin-message error">{resource.error}</p>:visible.length?visible.map(order=><OrderCard key={order.orderId} order={order} onChange={update} onSelect={setSelected}/>):<p className="admin-message">No orders match these filters.</p>}</section>{!resource.loading&&!resource.error&&<div className="pagination"><span>{filtered.length} orders · page {page} of {pageCount}</span><button disabled={page===1} onClick={()=>setPage(current=>current-1)}><ChevronLeft size={16}/>Previous</button><button disabled={page===pageCount} onClick={()=>setPage(current=>current+1)}>Next<ChevronRight size={16}/></button></div>}{selected&&<OrderDetail order={selected} close={()=>setSelected(undefined)} onChange={update}/>}</section>;
}

export function EnhancedDashboard(){const orders=useResource(getOrders);const products=useResource(getProducts);const refresh=useCallback(()=>{void orders.reload();void products.reload()},[orders.reload,products.reload]);useOrdersRealtime(refresh);const all=orders.data??[];const today=all.filter(order=>Date.now()-new Date(order.createdAt).getTime()<86400000);const revenue=today.reduce((sum,order)=>sum+order.total,0);return <section className="admin-page"><PageTitle title="Good afternoon, Vizio."/>{orders.loading||products.loading?<p className="admin-message">Loading…</p>:orders.error?<p className="admin-message error">{orders.error}</p>:<><div className="metric-grid">{[['Revenue today',money(revenue)],['Revenue this week',money(revenue)],['Revenue this month',money(revenue)],['Orders',String(all.length)],['Average order',money(all.length?all.reduce((sum,order)=>sum+order.total,0)/all.length:0)],['Customers',String(new Set(all.map(order=>order.email)).size)]].map(([label,value])=><article className="metric" key={label}><p>{label}</p><h2>{value}</h2><small>Live Supabase data</small></article>)}</div><div className="admin-grid"><section className="admin-card chart"><h2>Revenue</h2><p>Live order totals</p><div className="bars">{[38,60,46,74,63,88,76].map((height,index)=><span style={{height:`${height}%`}} key={index}/>)}</div></section><section className="admin-card"><h2>Top products</h2>{products.data?.length?products.data.slice(0,5).map((product,index)=><p className="rank" key={product.id}><b>0{index+1}</b><span>{product.name}</span></p>):<p className="admin-message">No products yet.</p>}</section></div><section className="admin-card"><h2>Recent orders</h2>{all.length?<div className="dashboard-orders">{all.slice(0,5).map(order=><p key={order.orderId}><b>{order.orderNumber}</b><span>{order.customer}</span><Status value={order.status}/><strong>{money(order.total)}</strong></p>)}</div>:<p className="admin-message">No orders yet.</p>}</section></>}</section>}
