-- Backwards-compatible management platform expansion.
alter table public.products add column if not exists available boolean not null default true, add column if not exists featured boolean not null default false, add column if not exists popular boolean not null default false, add column if not exists vegetarian boolean not null default false, add column if not exists vegan boolean not null default false, add column if not exists halal boolean not null default false, add column if not exists gluten_free boolean not null default false, add column if not exists preparation_time integer not null default 15 check (preparation_time >= 0), add column if not exists calories integer, add column if not exists ingredients text[] not null default '{}', add column if not exists allergens text[] not null default '{}', add column if not exists display_order integer not null default 0, add column if not exists image_url text, add column if not exists gallery_images text[] not null default '{}', add column if not exists archived_at timestamptz;
create index if not exists products_browse_idx on public.products(active, available, archived_at, display_order);
create table if not exists public.modifier_groups (id uuid primary key default gen_random_uuid(), name text not null, required boolean not null default false, min_selections smallint not null default 0, max_selections smallint, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.modifier_options (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.modifier_groups(id) on delete cascade, name text not null, price numeric(10,2) not null default 0, active boolean not null default true, display_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.product_modifier_groups (product_id uuid not null references public.products(id) on delete cascade, group_id uuid not null references public.modifier_groups(id) on delete cascade, primary key(product_id,group_id));
alter table public.restaurant_settings add column if not exists logo_url text, add column if not exists banner_url text, add column if not exists website text not null default '', add column if not exists facebook text not null default '', add column if not exists tiktok text not null default '', add column if not exists google_maps text not null default '', add column if not exists primary_colour text not null default '#7EA7D9', add column if not exists accent_colour text not null default '#E7C54A', add column if not exists currency text not null default 'AUD', add column if not exists timezone text not null default 'Australia/Perth', add column if not exists minimum_order numeric(10,2) not null default 0, add column if not exists pickup_time integer not null default 15, add column if not exists delivery_time integer not null default 35, add column if not exists order_prefix text not null default 'VF', add column if not exists receipt_footer text not null default '', add column if not exists kitchen_printer_name text not null default '';
create table if not exists public.favourite_products (user_id uuid not null references auth.users(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,product_id));
alter table public.modifier_groups enable row level security; alter table public.modifier_options enable row level security; alter table public.product_modifier_groups enable row level security; alter table public.favourite_products enable row level security;
create policy "public reads modifier groups" on public.modifier_groups for select using (true); create policy "public reads active modifier options" on public.modifier_options for select using (active=true); create policy "public reads product modifier groups" on public.product_modifier_groups for select using (true); create policy "users manage favourites" on public.favourite_products for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do nothing;
create policy "public reads product images" on storage.objects for select using (bucket_id='product-images');
create policy "staff manages product images" on storage.objects for all using (bucket_id='product-images' and public.is_admin());
